@echo off
echo Resetting project...

echo Removing old files...
if exist node_modules rmdir /s /q node_modules
if exist package-lock.json del package-lock.json
if exist dist rmdir /s /q dist

echo Installing dependencies...
npm install

echo Building project...
npm run build

echo Starting development server...
npm run dev
